version: '3'

volumes:
  postgres_data:

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: hibernate-issue
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
      ports:
        - 5432:5432
      networks:
        - network

networks:
  network:
    driver: bridge